image:
  registry: hanaservice-dev.common.repositories.cloud.sap
  repository: com.sap.hana.cloud.cloudinfrastructure/cloud-provider-exporter
  tag: v1.0.0
  pullPolicy: Always

name: cloud-provider-exporter
namespace: monitoring
enableServiceLinks: false
vaultToken: unset
k8sType: unset
region: unset
project: hc-dev
cloudProviderAccountVaultSubpath: unset
k8sClusterName: unset
vaultAddress: unset

cloudProviderExporter:
  replicas: 1
  containerPort: 8080
  resources:
    limits:
      memory: 2Gi
      cpu: 500m
    requests:
      memory: 1Gi
      cpu: 200m
  scrapingDuration: 60 # minutes
  cacheExpiration: 50
  cacheCleanupInterval: 90

config:
  vaultBackupBucket:
    prefix: etcd.backup
    bucket: vault-backup-bucket

  VaultConfig:
    vaultTokenFromEnv: false
    role: iaas-monitor

  AwsConfig:
    healthEventStatusCodes:
      - "open"
      - "upcoming"
      - "closed"
    healthEventTypeCategories:
      - "issue"
      - "accountNotification"
      - "scheduledChange"
    cloudwatchMetricsConf:
      discovery:
        exportedTagsOnMetrics:
          ec2:
            - Name
            - node.kubernetes.io/role
          ebs:
            - VolumeId
          nlb:
            - kubernetes.io/service-name
            - KubernetesCluster
          ngw:
            - Name
        jobs:
          - type: ec2
            length: 900
            delay: 120
            statistics:
              - Minimum
              - Maximum
              - Sum
            searchTags:
              - key: Name
                value: shoot--hc-dev--demo.*
            metrics:
              - name: CPUUtilization
                statistics:
                  - Average
                period: 600
                length: 172800
              - name: NetworkIn
                statistics:
                  - Average
                period: 600
                length: 600
              - name: NetworkOut
                statistics:
                  - Average
                period: 600
                length: 600
          - type: ebs
            searchTags:
              - key: Name
                value: shoot--hc-dev--demo.*
            metrics:
              - name: VolumeReadOps
                statistics:
                  - Average
                period: 600
                length: 600
              - name: VolumeWriteOps
                statistics:
                  - Average
                period: 600
                length: 600
              - name: VolumeWriteBytes
                statistics:
                  - Average
                period: 600
                length: 600
              - name: VolumeReadBytes
                statistics:
                  - Average
                period: 600
                length: 600
          - type: nlb
            searchTags:
              - key: KubernetesCluster
                value: shoot--hc-dev--demo.*
            metrics:
              - name: ActiveFlowCount
                statistics:
                  - Average
                period: 60
                length: 3600
              - name: PeakPacketsPerSecond
                statistics:
                  - Maximum
                period: 60
                length: 3600
              - name: ProcessedPackets
                statistics:
                  - Sum
                period: 60
                length: 3600
          - type: ngw
            searchTags:
              - key: Name
                value: shoot--hc-dev--demo.*
            metrics:
              - name: BytesInFromDestination
                statistics:
                  - Sum
                period: 300
                length: 3600
              - name: BytesInFromSource
                statistics:
                  - Sum
                period: 300
                length: 3600
              - name: BytesOutToDestination
                statistics:
                  - Sum
                period: 300
                length: 3600
              - name: BytesOutToSource
                statistics:
                  - Sum
                period: 300
                length: 3600

  GcpConfig:


  AzureConfig:
    subscriptionID: a68ae472-1849-4ed9-a700-24f5070acd2d

  AliCloudConfig:
    endpoint: oss-cn-hangzhou.aliyuncs.com

dashboards:
  name: cloud-provider
