{
 "title": "Cloud Provider Health Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "The Number of Health Events",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(cpe_health_events)", "legendFormat": "__auto" },
    {
     "expr": "sum(cpe_health_events_closed_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cpe_health_events_opened_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Types of Health Events",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (eventType) (cpe_health_events)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Types of Opened Health Events",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (eventType) (cpe_health_events{statusCode=\"open\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Affected Regions of Health Events",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (affectedRegions) (cpe_health_events_affected)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Affected Regions of Opened Health Events",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (affectedRegions) (cpe_health_events{statusCode=\"open\"}+ on(eventID) group_left(affectedRegions) cpe_health_events_affected)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Event",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "cpe_health_events", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Health Event Effect",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "cpe_health_events_affected", "legendFormat": "__auto" }
   ]
  }
 ]
}