{
 "title": "Cloud Provider Quota Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Quota Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpe_quota_current / on(QuotaCode) group_left() cpe_quota_limit{}",
     "legendFormat": "{{QuotaName}}"
    }
   ]
  },
  {
   "title": "Current Usage Value",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cpe_quota_current{}", "legendFormat": "{{QuotaName}}" }
   ]
  },
  {
   "title": "Limit Value",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "quota_limit{}", "legendFormat": "{{QuotaName}}" }
   ]
  }
 ]
}